services:
  - type: web
    name: hrmo
    env: docker
    plan: starter
    buildCommand: docker build -t hrmo .
    startCommand: docker run your-image-name
    dockerfilePath: docker/8.2/Dockerfile  # Ensure this is correct
